### PR TITLE
fix SprintsDashboard sprint sorting and date format

### LINKED ISSUE #273: Opiskelija näkee sprint dashboardille lisätyt sprintit suomlaisessa päivämääräformaatissa
Tällä hetkellä lisätyn sprintin päivmäärä näkyy muodossa yyyy-mm-dd, tämä muutetaan muotoon dd/mm/yyyy

### PR DESCRIPTION
**Pull request by miahro**
resolves #273 #252

Date format fixed to DD/MM/YYYY (consistent with form calendar selector). Sprints sorted in dashboard according to spring number (descending)

### CODE REVIEW

File: frontend/src/components/SprintsPage/SprintsDashboard.jsx [hunk 1]
```diff
@@ -151,24 +151,33 @@ const SprintsPage = (props) => {
...
-                    </Button>
-                  </td>
-                </tr>
-              ))}
+              {allSprints.sort((a, b) => b.sprint - a.sprint).map((sprint) => {
+
+                const startDateObj = new Date(sprint.start_date)
+                const endDateObj = new Date(sprint.end_date)
+
+                const formattedStartDate = `${startDateObj.getDate().toString().padStart(2, '0')}/${(startDateObj.getMonth() + 1).toString().padStart(2, '0')}/${startDateObj.getFullYear()}`
```
Comment (ismomehdi) [inline frontend/src/components/SprintsPage/SprintsDashboard.jsx:159]: You could make this a bit simpler by using:

const formattedDate = new Intl.DateTimeFormat('fi-FI').format(dateObj)

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat

**Review by ismomehdi — CHANGES_REQUESTED** [review]

File: frontend/src/components/SprintsPage/SprintsDashboard.jsx [hunk 2]
```diff
@@ -151,24 +151,33 @@ const SprintsPage = (props) => {
...
+                const formattedEndDate = `${endDateObj.getDate().toString().padStart(2, '0')}/${(endDateObj.getMonth() + 1).toString().padStart(2, '0')}/${endDateObj.getFullYear()}`
```
Comment (ismomehdi) [inline frontend/src/components/SprintsPage/SprintsDashboard.jsx:160]: Same here

**Review by ismomehdi — CHANGES_REQUESTED** [review]

File: frontend/src/components/SprintsPage/SprintsDashboard.jsx (hunk 1 above)
Comment (miahro) [reply frontend/src/components/SprintsPage/SprintsDashboard.jsx]: I tried first:
const formattedStartDate = new Intl.DateTimeFormat('fi-FI').format(startDateObj)

but this doesn't work directly, because standard fi-FI is DD.MM.YYYY and in form selector we have DD/MM/YYYY, and it looks silly to have two different formats in one view. 

But it is correct that my solution is not clear, I replaced with this which is much more readable: 

                const formattedStartDate = startDateObj.toLocaleDateString('fi-FI', {
                  day: '2-digit',
                  month: '2-digit',
                  year: 'numeric',
                }).replace(/\./g, '/')

Comment (ismomehdi) [reply frontend/src/components/SprintsPage/SprintsDashboard.jsx]: Ok, I didn't realise that!

**Review by ismomehdi — APPROVED** [review]
Great!
